#!/bin/sh
# quake2-server
# qui mai  7 16:15:54 EST 1998
#
# chkconfig: 345 98 10
# description: Ativa/Desativa servidor quake2
# Translated to Polish by fastviper

# Biblioteca de funções
# Biblioteka funkcyj
. /etc/rc.d/init.d/functions

HOME=/usr/lib/quake2

case "$1" in
  start)
	echo -n "Odpalamy serwer Quake2: "
        cd $HOME
	/usr/bin/quake2id +set dedicated 1 +exec server.cfg > /dev/null &
	echo
	;;
  stop)
	echo -n "Koñczymy dzia³anie serwera Quake2: "
	killall quake2id
	echo ""
	;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
	echo "Sposób: quake2-server {start|stop|restart}"
	exit 1
esac

exit 0
