#!/bin/sh
#
# chkconfig: 345 98 10
# description: dedicated quake2 server

# Functions library
. /etc/rc.d/init.d/functions

start() {
	# Check if the service is already running?
	if [ ! -f /var/lock/subsys/q2ded ]; then
		msg_starting "Quake2 server"
		busy
		su -s /bin/sh - quake2 -c "screen -dmS q2ded"
		RETVAL=$?
		if [ "$RETVAL" = 0 ]; then
			touch /var/lock/subsys/q2ded
			ok
		else
			fail
		fi
	else
		msg_already_running "Quake2 server"
	fi
}

stop() {
	if [ -f /var/lock/subsys/q2ded ]; then
		msg_stopping "Quake2 server"
		su -s /bin/sh - quake2 -c "screen -S q2ded -X quit > /dev/null" && ok || fail
		rm -f /var/lock/subsys/q2ded
	else
		msg_not_running "Quake2 server"
		exit 7
	fi
}

RETVAL=0
case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
	stop
	start
	;;
  status)
	status /usr/bin/quake2
	exit $?
	;;
  *)
	msg_Usage "$0 {start|stop|restart|status}"
	exit 3
esac

exit 0
