#!/bin/bash
# quake2 script for choosing graphics acceleration
# created by fastviper
. /etc/rc.d/init.d/functions

HOME=/usr/lib/quake2

case "$1" in
  svgalib)
	echo -n "Starting Quake2 using SVGALib Console Graphics: "
        cd $HOME
	/usr/bin/quake2id +set vid_ref soft > /dev/null &
	echo
	;;
  softwareX11)
	echo -n "Starting Quake2 using X11 Window Graphics (software renderer): "
        cd $HOME
	bind i "_windowed_mouse 1" > /dev/null &
	bind o "_windowed_mouse 0" > /dev/null &
	echo "Press i to use mouse inside of Quake2 window, press o to use it outside"
	/usr/bin/quake2id +set vid_ref softx > /dev/null &
	echo
	;;
  Mesa)
	echo -n "Starting Quake2 using 3DFX fxMesa with Mesa 3-D or 3DFX Miniport: "
        cd $HOME
	/usr/bin/quake2id +set vid_ref gl > /dev/null &
	echo "To force one of drivers you can use:"
	echo "/usr/bin/quake2id +set vid_ref gl +set gl_driver libMesaGL.so.2"
	echo "or:"
	echo "/usr/bin/quake2id +set vid_ref gl +set gl_driver lib3dfxgl.so"
	echo
	;;
  GLX)
	echo -n "Starting Quake2 using Generic OpenGL: "
        cd $HOME
	export MESA_GLX_FX=fullscreen
	/usr/bin/quake2id +set vid_ref glx > /dev/null &
	echo
	;;
  *)
	echo "Usage: quake2 {svgalib|softwareX11|Mesa|GLX}"
	exit 1
esac

exit 0
